# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(563, 432)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/EditorMode.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        Dialog.setStyleSheet("")
        self.tab_music = QtWidgets.QTabWidget(Dialog)
        self.tab_music.setEnabled(True)
        self.tab_music.setGeometry(QtCore.QRect(10, 40, 541, 381))
        self.tab_music.setObjectName("tab_music")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.levelString = QtWidgets.QLineEdit(self.tab_search)
        self.levelString.setGeometry(QtCore.QRect(120, 10, 301, 20))
        self.levelString.setToolTip("")
        self.levelString.setInputMask("")
        self.levelString.setText("")
        self.levelString.setObjectName("levelString")
        self.label_level = QtWidgets.QLabel(self.tab_search)
        self.label_level.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_level.setObjectName("label_level")
        self.searchLevel = QtWidgets.QPushButton(self.tab_search)
        self.searchLevel.setGeometry(QtCore.QRect(430, 10, 75, 23))
        self.searchLevel.setObjectName("searchLevel")
        self.level_info = QtWidgets.QTableWidget(self.tab_search)
        self.level_info.setGeometry(QtCore.QRect(10, 40, 511, 271))
        self.level_info.setObjectName("level_info")
        self.level_info.setColumnCount(1)
        self.level_info.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.level_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.level_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.level_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.level_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.level_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.level_info.setHorizontalHeaderItem(0, item)
        self.level_info.horizontalHeader().setCascadingSectionResizes(False)
        self.level_info.horizontalHeader().setDefaultSectionSize(100)
        self.level_info.horizontalHeader().setStretchLastSection(True)
        self.level_info.verticalHeader().setCascadingSectionResizes(False)
        self.level_info.verticalHeader().setDefaultSectionSize(47)
        self.level_info.verticalHeader().setMinimumSectionSize(10)
        self.level_info.verticalHeader().setSortIndicatorShown(False)
        self.level_info.verticalHeader().setStretchLastSection(True)
        self.downloadSong = QtWidgets.QPushButton(self.tab_search)
        self.downloadSong.setGeometry(QtCore.QRect(10, 320, 171, 23))
        self.downloadSong.setObjectName("downloadSong")
        self.listensong = QtWidgets.QPushButton(self.tab_search)
        self.listensong.setGeometry(QtCore.QRect(190, 320, 75, 23))
        self.listensong.setObjectName("listensong")
        self.btn_hax_copy = QtWidgets.QPushButton(self.tab_search)
        self.btn_hax_copy.setGeometry(QtCore.QRect(450, 320, 75, 23))
        self.btn_hax_copy.setObjectName("btn_hax_copy")
        self.tab_music.addTab(self.tab_search, "")
        self.tab_local_music = QtWidgets.QWidget()
        self.tab_local_music.setObjectName("tab_local_music")
        self.list_songs = QtWidgets.QListWidget(self.tab_local_music)
        self.list_songs.setGeometry(QtCore.QRect(10, 40, 511, 251))
        self.list_songs.setViewMode(QtWidgets.QListView.ListMode)
        self.list_songs.setSelectionRectVisible(False)
        self.list_songs.setObjectName("list_songs")
        self.songString = QtWidgets.QLineEdit(self.tab_local_music)
        self.songString.setGeometry(QtCore.QRect(100, 10, 231, 20))
        self.songString.setObjectName("songString")
        self.label_5 = QtWidgets.QLabel(self.tab_local_music)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.label_5.setObjectName("label_5")
        self.searchSong = QtWidgets.QPushButton(self.tab_local_music)
        self.searchSong.setGeometry(QtCore.QRect(340, 10, 75, 23))
        self.searchSong.setObjectName("searchSong")
        self.song_timeStamp = QtWidgets.QLabel(self.tab_local_music)
        self.song_timeStamp.setGeometry(QtCore.QRect(420, 310, 51, 21))
        self.song_timeStamp.setAlignment(QtCore.Qt.AlignCenter)
        self.song_timeStamp.setObjectName("song_timeStamp")
        self.songbar = QtWidgets.QSlider(self.tab_local_music)
        self.songbar.setEnabled(True)
        self.songbar.setGeometry(QtCore.QRect(154, 310, 261, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songbar.sizePolicy().hasHeightForWidth())
        self.songbar.setSizePolicy(sizePolicy)
        self.songbar.setMinimumSize(QtCore.QSize(0, 0))
        self.songbar.setSizeIncrement(QtCore.QSize(0, 0))
        self.songbar.setBaseSize(QtCore.QSize(0, 0))
        self.songbar.setMinimum(0)
        self.songbar.setMaximum(100)
        self.songbar.setProperty("value", 0)
        self.songbar.setTracking(False)
        self.songbar.setOrientation(QtCore.Qt.Horizontal)
        self.songbar.setInvertedAppearance(False)
        self.songbar.setInvertedControls(False)
        self.songbar.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.songbar.setTickInterval(0)
        self.songbar.setObjectName("songbar")
        self.playSong = QtWidgets.QPushButton(self.tab_local_music)
        self.playSong.setEnabled(True)
        self.playSong.setGeometry(QtCore.QRect(64, 310, 75, 23))
        self.playSong.setObjectName("playSong")
        self.deleteSong = QtWidgets.QPushButton(self.tab_local_music)
        self.deleteSong.setGeometry(QtCore.QRect(420, 10, 75, 23))
        self.deleteSong.setObjectName("deleteSong")
        self.tab_music.addTab(self.tab_local_music, "")
        self.tab_local_levels = QtWidgets.QWidget()
        self.tab_local_levels.setObjectName("tab_local_levels")
        self.table_local_levels = QtWidgets.QTableWidget(self.tab_local_levels)
        self.table_local_levels.setGeometry(QtCore.QRect(10, 10, 511, 291))
        self.table_local_levels.setObjectName("table_local_levels")
        self.table_local_levels.setColumnCount(4)
        self.table_local_levels.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_local_levels.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_local_levels.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_local_levels.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_local_levels.setHorizontalHeaderItem(3, item)
        self.btn_verify_hack = QtWidgets.QPushButton(self.tab_local_levels)
        self.btn_verify_hack.setGeometry(QtCore.QRect(10, 310, 91, 23))
        self.btn_verify_hack.setObjectName("btn_verify_hack")
        self.btn_load_local_levels = QtWidgets.QPushButton(self.tab_local_levels)
        self.btn_load_local_levels.setGeometry(QtCore.QRect(434, 310, 81, 23))
        self.btn_load_local_levels.setObjectName("btn_load_local_levels")
        self.tab_music.addTab(self.tab_local_levels, "")
        self.tab_mmscript = QtWidgets.QWidget()
        self.tab_mmscript.setObjectName("tab_mmscript")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_mmscript)
        self.lineEdit.setGeometry(QtCore.QRect(100, 10, 121, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.tab_mmscript)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_mmscript)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_mmscript)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_mmscript)
        self.checkBox.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_mmscript)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 140, 111, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_mmscript)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 160, 101, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_mmscript)
        self.textEdit.setGeometry(QtCore.QRect(10, 230, 231, 111))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.tab_mmscript)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_mmscript)
        self.pushButton.setGeometry(QtCore.QRect(440, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.tab_mmscript)
        self.progressBar.setGeometry(QtCore.QRect(257, 320, 171, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.tab_mmscript)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 81, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_mmscript)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 70, 21, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_mmscript)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 230, 21, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tab_music.addTab(self.tab_mmscript, "")
        self.tab_help = QtWidgets.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_help)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 511, 121))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.tab_music.addTab(self.tab_help, "")
        self.tab_credits = QtWidgets.QWidget()
        self.tab_credits.setObjectName("tab_credits")
        self.label_disclaimer = QtWidgets.QLabel(self.tab_credits)
        self.label_disclaimer.setGeometry(QtCore.QRect(10, 10, 491, 221))
        self.label_disclaimer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_disclaimer.setWordWrap(True)
        self.label_disclaimer.setObjectName("label_disclaimer")
        self.label_copy = QtWidgets.QLabel(self.tab_credits)
        self.label_copy.setGeometry(QtCore.QRect(190, 300, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_copy.setFont(font)
        self.label_copy.setObjectName("label_copy")
        self.btn_accept = QtWidgets.QPushButton(self.tab_credits)
        self.btn_accept.setEnabled(False)
        self.btn_accept.setGeometry(QtCore.QRect(230, 260, 75, 23))
        self.btn_accept.setObjectName("btn_accept")
        self.check_use = QtWidgets.QCheckBox(self.tab_credits)
        self.check_use.setEnabled(True)
        self.check_use.setGeometry(QtCore.QRect(120, 230, 301, 17))
        self.check_use.setObjectName("check_use")
        self.tab_music.addTab(self.tab_credits, "")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setStyleSheet("")
        self.title.setScaledContents(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")

        self.retranslateUi(Dialog)
        self.tab_music.setCurrentIndex(3)
        self.check_use.toggled['bool'].connect(self.btn_accept.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tab_music, self.songString)
        Dialog.setTabOrder(self.songString, self.searchSong)
        Dialog.setTabOrder(self.searchSong, self.songbar)
        Dialog.setTabOrder(self.songbar, self.list_songs)
        Dialog.setTabOrder(self.list_songs, self.playSong)
        Dialog.setTabOrder(self.playSong, self.deleteSong)
        Dialog.setTabOrder(self.deleteSong, self.levelString)
        Dialog.setTabOrder(self.levelString, self.searchLevel)
        Dialog.setTabOrder(self.searchLevel, self.level_info)
        Dialog.setTabOrder(self.level_info, self.downloadSong)
        Dialog.setTabOrder(self.downloadSong, self.listensong)
        Dialog.setTabOrder(self.listensong, self.btn_hax_copy)
        Dialog.setTabOrder(self.btn_hax_copy, self.table_local_levels)
        Dialog.setTabOrder(self.table_local_levels, self.btn_verify_hack)
        Dialog.setTabOrder(self.btn_verify_hack, self.btn_accept)
        Dialog.setTabOrder(self.btn_accept, self.check_use)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GDMT v2"))
        self.label_level.setText(_translate("Dialog", "Nombre o id del nivel:"))
        self.searchLevel.setText(_translate("Dialog", "Buscar"))
        item = self.level_info.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Id del nivel"))
        item = self.level_info.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.level_info.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "Descripción"))
        item = self.level_info.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "Creador"))
        item = self.level_info.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "Music"))
        item = self.level_info.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Datos del nivel"))
        self.downloadSong.setText(_translate("Dialog", "Descargar canción"))
        self.listensong.setText(_translate("Dialog", "Escuchar"))
        self.btn_hax_copy.setText(_translate("Dialog", "Copiar nivel"))
        self.tab_music.setTabText(self.tab_music.indexOf(self.tab_search), _translate("Dialog", "Buscar nivel"))
        self.label_5.setText(_translate("Dialog", "Buscar canción:"))
        self.searchSong.setText(_translate("Dialog", "Buscar"))
        self.song_timeStamp.setText(_translate("Dialog", "00:00"))
        self.playSong.setText(_translate("Dialog", "Reproducir"))
        self.deleteSong.setText(_translate("Dialog", "Eliminar"))
        self.tab_music.setTabText(self.tab_music.indexOf(self.tab_local_music), _translate("Dialog", "Música descargada"))
        item = self.table_local_levels.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nombre"))
        item = self.table_local_levels.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Descripción"))
        item = self.table_local_levels.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Canción"))
        item = self.table_local_levels.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Duración"))
        self.btn_verify_hack.setText(_translate("Dialog", "Verificar"))
        self.btn_load_local_levels.setText(_translate("Dialog", "Cargar niveles"))
        self.tab_music.setTabText(self.tab_music.indexOf(self.tab_local_levels), _translate("Dialog", "Niveles locales"))
        self.label.setText(_translate("Dialog", "Id del nivel:"))
        self.label_2.setText(_translate("Dialog", "Layout group id:"))
        self.checkBox.setText(_translate("Dialog", "Mostrar porcentaje"))
        self.checkBox_2.setText(_translate("Dialog", "Mostrar comentario"))
        self.checkBox_3.setText(_translate("Dialog", "Mostrar usuario"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">#ITEM</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">size:0.25,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">group:1;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">#GLOBAL</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">alpha:1|0.5;</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Customizar objetos"))
        self.pushButton.setText(_translate("Dialog", "Ejecutar"))
        self.label_4.setText(_translate("Dialog", "(debe ser tuyo)"))
        self.pushButton_2.setText(_translate("Dialog", "?"))
        self.pushButton_3.setText(_translate("Dialog", "?"))
        self.tab_music.setTabText(self.tab_music.indexOf(self.tab_mmscript), _translate("Dialog", "MM Script"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "Indice"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Dialog", "MM Script"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Dialog", "Concepto"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Dialog", "Parámetros"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("Dialog", "Layout id"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("Dialog", "Customizar objetos"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tab_music.setTabText(self.tab_music.indexOf(self.tab_help), _translate("Dialog", "Ayuda"))
        self.label_disclaimer.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Documentación y código fuente disponible en </span><a href=\"https://github.com/Bubbr/gd-tool\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">GitHub.</span></a></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Este programa es totalmente gratuito y sin fines de lucro. Es únicamente para fines educativos y pedimos a todos los usuarios que no lo utilicen para su propio beneficio. Por ejemplo, si tienen que verificar un nivel, no hagan uso de este programa y proclamen como suya dicha verificación, esto con el objetivo de crear una comunidad sana y que no este llena de </span><a href=\"https://es.wikipedia.org/wiki/Script_kiddie\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline; color:#0000ff;\">scripts kiddies</span></a><span style=\" font-family:\'MS Shell Dlg 2\';\"> que buscan fama.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">El objetivo de este proyecto es exprimir las capacidades del juego y con ello hacer sorprendentes creaciones que beneficiaran a la comunidad y no la afectaran, este proyecto esta basado en la curiosidad y en expandir el conocimiento.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Cualquier duda o sugerencia pueden enviarme un e-mail al siguiente correo correoejemploxd.gmail.com.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Apoya a la comunidad y no la perjudiques. ;)</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Atentamente: ~Un tipo random de Internet~</span></p></body></html>"))
        self.label_copy.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Geometry Dash Multi-Tool v2</p></body></html>"))
        self.btn_accept.setText(_translate("Dialog", "Continuar"))
        self.check_use.setText(_translate("Dialog", "Acepto que no usaré este programa para fines maliciosos."))
        self.tab_music.setTabText(self.tab_music.indexOf(self.tab_credits), _translate("Dialog", "Aviso de uso"))
        self.title.setText(_translate("Dialog", "Geometry Dash Multi-Tool v2"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
